### ISSUE TITLE
Remove size onhover tagcloud item

### ISSUE THREAD

**Issue by gleidiin** [alhazmy13/Angular4-word-cloud#3]
Hi Guys,

I was testing the angular word could and I have a little difficuty to remove the size under the tagcloud, is there a way to do this using the current config? And more, in the documentation  says the attribuite "colors" exists in directive, and the correctly  is "color".

**Comment by gleidiin** [comment]
Hi @sangwin, thanks for help. It worked for me :)

**Comment by alhazmy13** [comment]
Hi @gleidiin 
Thanks four your report, this issue should be fixed with version `1.0.1`

**Comment by gleidiin** [comment]
@alhazmy13 if you give me a chance I can do it. :)

**Comment by sangwin** [comment]
Glad I could help. :)
