### ISSUE TITLE
plunkr demo not working

### ISSUE THREAD

**Issue by Lakston** [alhazmy13/Angular4-word-cloud#6]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The plunkr demo is not working

## What is the motivation / use case for changing the behavior?
I'd like to check out this repo but the I can't see the demo to see if I would be interested in using it :)

**Comment by alhazmy13** [comment]
Hi @Lakston 
Please double check again, it works fine.

Please Let me if the issue still occurs with you.
Thanks.

**Comment by sangwin** [comment]
Yes. [Plunkr](https://embed.plnkr.co/hSoU4QbvVmKCdnG9Tw1h/) is working fine.

**Comment by Lakston** [comment]
Still not working : 

```
zone.js:392 Error: (SystemJS) Error: XHR error loading https://unpkg.com/rxjs/operators/refCount.js
	    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.8.18/dist/zone.js:425:31)
	    at Zone.runTask (https://unpkg.com/zone.js@0.8.18/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (https://unpkg.com/zone.js@0.8.18/dist/zone.js:499:34)
	    at invokeTask (https://unpkg.com/zone.js@0.8.18/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (https://unpkg.com/zone.js@0.8.18/dist/zone.js:1566:17)
	Error loading https://unpkg.com/rxjs/operators/refCount.js as "./refCount" from https://unpkg.com/rxjs/operators/share.js
```

**Comment by sangwin** [comment]
Are you facing this issue on live [URL](https://embed.plnkr.co/hSoU4QbvVmKCdnG9Tw1h/)?

**Comment by Lakston** [comment]
Yes, chrome latest, osx, if that helps.

**Comment by anuj509** [comment]
not working.Anyone found solution or Alternative.

**Comment by Lakston** [comment]
Oh wow, it appears I was still subscribed here, my solution was to use something else, we went with echarts + echarts wordcloud.
