### ISSUE TITLE
Wordcloud data dynamic update issue.

### ISSUE THREAD

**Issue by NareshSmith** [alhazmy13/Angular4-word-cloud#7]
Please provide a solution for updating a WordCloud Data Dynamically.

**Comment by alhazmy13** [comment]
Hi @NareshSmith 
Please use the last version v1.0.4 and check the readme file, there's a new example to set the data Dynamically.

Thanks

**Comment by NareshSmith** [comment]
another issue which am facing is , Responsive not working. when on resizing window, word cloud size remains same and not able to set its width in '%'.
